version: 0.3.3-build{build}
skip_non_tags: true
os: Visual Studio 2015
shallow_clone: true

branches: 
  except:
  - screenshots

configuration: Release

environment:
  mrhash_version: 0.3.3
  #boost_dir: C:\Libraries\boost_1_69_0
  msvc_dir: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
  
  matrix:
  #MSVC x86
  - name: win32
    arch: x86
    vc_arch: x86
    target: mrhash.exe
    qt_version: 5.11.3
    qt_dir: C:\Qt\%qt_version%\msvc2015\bin
    
  #MSVC x64
  - name: win64
    arch: x64
    vc_arch: amd64
    target: mrhash64.exe
    qt_version: 5.13.2
    qt_dir: C:\Qt\%qt_version%\msvc2015_64\bin
    
clone_script:
    - cmd: git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
    - cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%

init:
    - set PATH=%PATH%;%msvc_dir%;%qt_dir%
    - vcvarsall.bat %vc_arch%
    
install:
    - mkdir lib
    - cd lib
    - mkdir qtcryptohash
    - appveyor DownloadFile https://github.com/rikyoz/QtCryptoHash/releases/download/v0.1.2/QtCryptoHash-v0.1.2-msvc2015-win32-static.7z -FileName qtcryptohash-static.7z 
    - 7z x qtcryptohash-static.7z -oqtcryptohash/ -aoa
    - appveyor DownloadFile https://github.com/rikyoz/QtCryptoHash/releases/download/v0.1.2/QtCryptoHash-v0.1.2-msvc2015-win64-static.7z -FileName qtcryptohash64-static.7z
    - 7z x qtcryptohash64-static.7z -oqtcryptohash/ -aoa
    - cd ..
    
build_script:
    - mkdir build
    - cd build
    - qmake ..\MrHash.pro "CONFIG += release"
    - nmake release
    - cd ..\bin\%arch%\release
    - windeployqt %target% --release --no-translations --no-svg --no-angle --no-system-d3d-compiler --no-quick-import
    - 7z a -t7z mrhash-v%mrhash_version%-bin-%name%.7z *
    
artifacts:
    - path: bin\**\*.7z
      name: binary

test: off

deploy:
    provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Binaries of Mr. Hash v%mrhash_version%'
    auth_token:
      secure: 4V5xJQT+iVPUhK05TBLkNkLY8HTArZ+omH394hfXqQuxfrkaQqnR8132rDnB/HVm
    artifact: /.*\.7z/
    draft: true
    prerelease: false
    on:
      # branch: master
      appveyor_repo_tag: true