version: 0.3.1-dev{build}
#skip_non_tags: true
os: Windows Server 2012 R2
shallow_clone: true

branches:
  only:
  - master
  - develop
  
configuration:
  - release

environment:
  mrhash_version: 0.3.0
  qt_version: 5.5
  boost_dir: C:\Libraries\boost_1_59_0
  msvc_dir: C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC
  
  matrix:
  #MSVC x86
  - name: win32
    platform: x86
    target: mrhash.exe
    qt_dir: C:\Qt\%qt_version%\msvc2013\bin
    
  #MSVC x64
  - name: win64
    platform: x64
    target: mrhash64.exe
    qt_dir: C:\Qt\%qt_version%\msvc2013_64\bin

init:
    - set PATH=%PATH%;%msvc_dir%;%qt_dir%
    - vcvarsall.bat %platform%
    #- mkdir lib
    - mklink /j lib\boost %boost_dir%\boost
    - cd lib
    - set PATH=.;%PATH%
    - mkdir qtcryptohash
    - dependencies.cmd

build_script:
    - mkdir build
    - cd build
    - qmake ..\MrHash.pro
    - nmake release
    - cd ..\bin\%platform%\release
    - windeployqt %target% --release --no-translations --no-svg --no-angle --no-system-d3d-compiler --no-quick-import
    - 7z a -t7z mrhash-v%mrhash_version%-bin-%name%.7z *
    
artifacts:
    - path: bin\**\*.7z
      name: binary

test: off

deploy:
    provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Binaries of Mr. Hash v%mrhash_version%'
    auth_token:
      secure: 4V5xJQT+iVPUhK05TBLkNkLY8HTArZ+omH394hfXqQuxfrkaQqnR8132rDnB/HVm
    artifact: /.*\.7z/
    draft: true
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true